apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: awesome-python-ai-image-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: awesome-python-ai-image-function
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/fklein82/awesome-ai-python-function.git
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
